### ISSUE TITLE
Readme is not compatible with license

### ISSUE THREAD

**Issue by Yazwh0** [zeropolis79/PETSCIIRobots-X16#1]
The restrictions imposed by the readme aren't compatible with those of the GPL.

**Comment by zeropolis79** [comment]
I'm working on that - I'm trying to find out how to change the licencing without deleting the existing archives and starting over

**Comment by Yazwh0** [comment]
Just change the license file to whatever you want to use, commit and merge.

Here is a good place to start: https://choosealicense.com/

**Comment by Yazwh0** [comment]
Or for non-commercial ones: https://creativecommons.org/about/cclicenses/

**Comment by zeropolis79** [comment]
OK - I've managed to delete the existing LICENCE file and created a new one - please let me know what you think:

https://github.com/zeropolis79/PETSCIIRobots-X16/blob/main/LICENCE

**Comment by Frosty-J** [comment]
It's generally recommended to use an existing licence, such as linked above, as they've been tried and tested and protect you from liabilities.

But at least this one is rather easy to read. I'd suggest fixing the typos ("curtesy", "distribte", "forbiden") and tidy up the "free to freely" wording.

**Comment by jrivard** [comment]
> It's generally recommended to use an existing licence, such as linked above, as they've been tried and tested and protect you from liabilities.

I was pondering doing a port as well, but the non-standard license is a road block.  If the copyright owners are interested in developing a community around the source I'd strongly recommend a standard license.

**Comment by zeropolis79** [comment]
If someone can recommend which licence to use, I'm all ears..

jrivard - if you want to port it, you can as long as you don't sell it.

**Comment by jrivard** [comment]
> If someone can recommend which licence to use, I'm all ears..
> 
> jrivard - if you want to port it, you can as long as you don't sell it.

Thanks, I appreciate the gesture, but I really would prefer a standard license.  The copyright owner should select one based on their requirements, and the link above to https://choosealicense.com/ is a great starting place.  As someone who originally waved my hands at this process as well, I can tell you from experience it is worth the small time investment to do this proper.

**Comment by zeropolis79** [comment]
I'm going to research this and talk with David about it - I'm hosting the source code on behalf of him. Looking at the licences, it looks like GNU GPLv3 would be the best one.. I will keep you posted, but out of interest, what system were you thinking of porting it to.

**Comment by zeropolis79** [comment]
@jrivard - the licence is going to be a GNU GPLv3 which i'm going to set up later.

**Comment by zeropolis79** [comment]
I'm working on a new licence..
